on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python requirements
        run: |
          pip install -r requirements.txt
      - name: Test
        run: |
          pytest --doctest-modules
